name: AdvancementCompetition
version: '${project.version}'
main: com.kamesuta.advancementcompetition.AdvancementCompetition
api-version: '1.20'
depend:
  - ProtocolLib

permissions:
  advancementcompetition.command.admin:
    description: Allows the player to use the admin command
    default: op

  advancementcompetition.command.adv:
    description: Allows the player to see player's advancements
    default: true

commands:
  adv:
    description: Main command for AdvancementCompetition
    usage: /adv [admin]
    permission: advancementcompetition.command.adv

  adv_place:
    description: Place an advancement
    usage: /adv_place <advancement>
    permission: advancementcompetition.command.admin
