name: AdvancementRanking
version: '${project.version}'
main: com.kamesuta.advrank.AdvancementRankingPlugin
api-version: '1.20'
depend:
  - ProtocolLib

permissions:
  advrank.admin:
    description: Allows the player to use the admin command
    default: op

  advrank.command.adv:
    description: Allows the player to see other player's advancements
    default: true

  advrank.command.adv_id:
    description: Allows the player to see the IDs of advancements
    default: true

  advrank.command.adv_rank:
    description: Allows the player to see advancement rankings
    default: true

commands:
  adv_admin:
    description: Admin commands for advancement ranking plugin
    usage: /adv_admin <subcommand>
    permission: advrank.admin

  adv:
    description: Show player's advancements
    usage: /adv <player>
    permission: advrank.command.adv

  adv_id:
    description: Show ID of the advancements
    usage: /adv_id
    permission: advrank.command.adv_id

  adv_rank:
    description: Show advancement rankings
    usage: /adv_rank <ID> [page]
    permission: advrank.command.adv_rank
