name: AdvancementCompetition
version: '${project.version}'
main: com.kamesuta.advancementcompetition.AdvancementCompetition
api-version: '1.20'
depend:
  - ProtocolLib

permissions:
  advancementcompetition.command.admin:
    description: Allows the player to use the admin command
    default: op

  advancementcompetition.command.adv:
    description: Allows the player to see player's advancements
    default: true

commands:
  adv:
    description: Show player's advancements
    usage: /adv <player>
    permission: advancementcompetition.command.adv

  adv_id:
    description: Show ID of the advancements
    usage: /adv_id
    permission: advancementcompetition.command.adv
